server:
  port: 8081

spring:
  application:
    name: auth-biblioteca

  datasource:
    url: jdbc:postgresql://localhost:5431/livros
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

    security:
      api.security.token.secret="${JWT_SECRET:my-secret-key}"

